sudo: false

language: python

matrix:
  include:
    # Python 3.6 on Linux
    - python: "3.6"
      os: "linux"
      dist: trusty
      env: TOXENV=py36

    # Python 3.7-dev on Linux
    - python: "3.7-dev"
      os: "linux"
      dist: trusty
      env: TOXENV=py37

    # Python 3.6 on OSX
    - os: "osx"
      language: generic
      env: TOXENV=py36

    # PyPy3 v? on Linux
    - python: "pypy3"
      os: "linux"
      dist: trusty
      env: TOXENV=pypy3

    # Linters
    - python: "3.6"
      os: "linux"
      dist: trusty
      env: TOXENV=linters

  allow_failures:
    - python:
      - "pypy3"
      - "3.7-dev"
    - os: "osx"

cache:
  directories:
    - $PWD/wheelhouse  # cache wheels so that we don't hit network everytime
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse

install: ./.travis/install.sh
script: tox